### ISSUE TITLE
为什么我下载下来没有效果

### ISSUE THREAD

**Issue by DaveBoy** [feelschaotic/AopClearLog#1]
就删除了jackOptions和rn的配置
提高gradle的版本到了3.5.0-beta05
添加了google仓库
日志依然有输出

**Comment by feelschaotic** [comment]
你好，日志依然有输出 说明 APT处理器 没有生效，需要检查是否有以下可能：
1. 没有注册成功（在`ClearLogProcessor`的`init`中使用 `mMessager.printMessage`打印看是否成功打印，证明拦截了编译过程）
2. 没有扫描到Log（debug `isLogStatements`方法是否有匹配到，如果你改了log打印，就需要修改对应的匹配前缀）

**Comment by qhzxz** [comment]
同样没效果啊；
Messager打印了LogClearTranslator里的信息，在../AptDemo/build/intermediates/classes/文件夹下的生成的MainActivity.class文件里也没有了Log方法，但是生成的Apk里还是没有把Log方法消除掉。

**Comment by DaveBoy** [comment]
算了  弄了半天也没成功  我还是找其他资料吧

**Comment by feelschaotic** [comment]
我估计最可能的原因是你那边`env instanceof JavacProcessingEnvironment`返回了false，导致没有拿到AST树，debug看看？

**Comment by qhzxz** [comment]
经过反复的尝试，发现是gradle版本和Android Studio版本会有影响，但具体怎么回事也不清楚。
我把Up主的Demo里的gradle版本切换到4.10.3然后将Android Studio升级到3.4.1就好了。
你可以先看一看aptprocessor工程下生成的jar包里有没有meta-inf文件夹如果没有说明可能是
gradle版本问题，然后aptprocessor工程的配置可以去参考butter-knife里的compiler模块。如果jar包里有meta-inf文件还是没有效果，再尝试把Android Studio 升级到3.4.1。
