### ISSUE TITLE
不支持kotlin么？

### ISSUE THREAD

**Issue by Aarontaken** [feelschaotic/AopClearLog#3]
工程中加了kotlin支持后，发现即使编译时的警告信息能打出来，但是生成的class文件中log没有清除，请问有研究么？

**Comment by feelschaotic** [comment]
暂不支持，除了kotlin编译器，官方没有提供操作Kotlin AST的API，需要自己手动解析，所以我没有加入kotlin的支持。这里有些资料，希望对你有所帮助：

https://stackoverflow.com/questions/32664842/how-to-get-kotlin-ast
https://discuss.kotlinlang.org/t/kotlin-ast/98
